export type TourRole = 'admin' | 'supervisor' | 'client';

export interface TourStep {
  id: string;
  role: TourRole;
  route?: string;
  selector?: string;
  title: string;
  body: string;
  placement?: 'top' | 'bottom' | 'left' | 'right' | 'center';
  mobilePlacement?: 'bottom' | 'center' | 'top';
  highlightPadding?: number;
  autoNavigate?: boolean;
}

export const TOUR_VERSION = 'v1';

const normalizePath = (path: string) => {
  if (!path) return '/';
  const trimmed = path.replace(/\/+$/, '');
  return trimmed === '' ? '/' : trimmed;
};

export const matchTourRoute = (pathname: string, route?: string) => {
  if (!route || route === '*') return true;
  const cleanPath = normalizePath(pathname);
  const cleanRoute = normalizePath(route);
  if (cleanRoute.includes(':')) {
    const pattern = `^${cleanRoute.replace(/:[^/]+/g, '[^/]+')}$`;
    return new RegExp(pattern).test(cleanPath);
  }
  return cleanPath === cleanRoute;
};

export const onboardingStepsByRole: Record<TourRole, TourStep[]> = {
  admin: [
    {
      id: 'admin-dashboard-projects',
      role: 'admin',
      route: '/admin/dashboard',
      selector: '[data-tour="admin-dashboard-projects"]',
      title: 'Proyectos activos',
      body: 'Cantidad de proyectos en operación. Puedes hacer clic para ir al listado de proyectos.',
      placement: 'bottom',
    },
    {
      id: 'admin-dashboard-clients',
      role: 'admin',
      route: '/admin/dashboard',
      selector: '[data-tour="admin-dashboard-clients"]',
      title: 'Clientes activos',
      body: 'Total de empresas clientes vigentes. Puedes hacer clic para ir al listado de clientes.',
      placement: 'bottom',
    },
    {
      id: 'admin-dashboard-total-scaffolds',
      role: 'admin',
      route: '/admin/dashboard',
      selector: '[data-tour="admin-dashboard-total-scaffolds"]',
      title: 'Total de andamios',
      body: 'Cantidad total de andamios reportados. Puedes hacer clic para ver el detalle.',
      placement: 'bottom',
    },
    {
      id: 'admin-dashboard-new-scaffolds',
      role: 'admin',
      route: '/admin/dashboard',
      selector: '[data-tour="admin-dashboard-new-scaffolds"]',
      title: 'Nuevos (24h)',
      body: 'Andamios creados en las últimas 24 horas.',
      placement: 'bottom',
    },
    {
      id: 'admin-dashboard-m3-total',
      role: 'admin',
      route: '/admin/dashboard',
      selector: '[data-tour="admin-dashboard-m3-total"]',
      title: 'Total m³',
      body: 'Volumen total reportado en el proyecto.',
      placement: 'bottom',
    },
    {
      id: 'admin-dashboard-m3-assembled',
      role: 'admin',
      route: '/admin/dashboard',
      selector: '[data-tour="admin-dashboard-m3-assembled"]',
      title: 'm³ armados',
      body: 'Volumen correspondiente a andamios ya armados.',
      placement: 'bottom',
    },
    {
      id: 'admin-dashboard-m3-progress',
      role: 'admin',
      route: '/admin/dashboard',
      selector: '[data-tour="admin-dashboard-m3-progress"]',
      title: 'm³ en proceso',
      body: 'Volumen de andamios que aún están en armado.',
      placement: 'bottom',
    },
    {
      id: 'admin-dashboard-m3-disassembled',
      role: 'admin',
      route: '/admin/dashboard',
      selector: '[data-tour="admin-dashboard-m3-disassembled"]',
      title: 'm³ desarmados',
      body: 'Volumen de andamios desmontados.',
      placement: 'bottom',
    },
    {
      id: 'admin-dashboard-status-card',
      role: 'admin',
      route: '/admin/dashboard',
      selector: '[data-tour="admin-dashboard-status-card"]',
      title: 'Andamios por estado',
      body: 'Distribución de andamios entre armados, en proceso y desarmados.',
      placement: 'top',
    },
    {
      id: 'admin-dashboard-safety-card',
      role: 'admin',
      route: '/admin/dashboard',
      selector: '[data-tour="admin-dashboard-safety-card"]',
      title: 'Tarjetas de seguridad',
      body: 'Resumen de tarjetas verdes y rojas para control de seguridad.',
      placement: 'top',
    },
    {
      id: 'admin-clients-create',
      role: 'admin',
      route: '/admin/clients',
      selector: '[data-tour="admin-clients-create"]',
      title: 'Empresas cliente',
      body: 'Crea la empresa cliente para luego asociar proyectos y usuarios.',
      placement: 'bottom',
    },
    {
      id: 'admin-users-create',
      role: 'admin',
      route: '/admin/users',
      selector: '[data-tour="admin-users-create"]',
      title: 'Usuarios',
      body: 'Crea el usuario cliente y/o supervisor para operar el proyecto.',
      placement: 'bottom',
    },
    {
      id: 'admin-projects-create',
      role: 'admin',
      route: '/admin/projects',
      selector: '[data-tour="admin-projects-create"]',
      title: 'Proyectos',
      body: 'Crea el proyecto y vincúlalo con la empresa cliente.',
      placement: 'bottom',
    },
    {
      id: 'admin-projects-assign',
      role: 'admin',
      route: '/admin/projects',
      selector: '[data-tour="admin-projects-assign"]',
      title: 'Asignaciones',
      body: 'Asigna usuarios al proyecto (cliente y supervisor).',
      placement: 'top',
    },
    {
      id: 'admin-scaffolds',
      role: 'admin',
      route: '/admin/scaffolds',
      selector: '[data-tour="admin-scaffolds"]',
      title: 'Andamios y reportes',
      body: 'Desde aquí puedes revisar reportes, exportar y auditar avances.',
      placement: 'bottom',
    },
    {
      id: 'admin-tour-launcher',
      role: 'admin',
      route: '*',
      selector: '[data-tour="tour-launcher"]',
      title: '¿Necesitas ayuda?',
      body: 'Este botón siempre te permite reabrir la guía cuando la necesites.',
      placement: 'top',
      mobilePlacement: 'top',
    },
  ],
  supervisor: [
    {
      id: 'sup-projects-select',
      role: 'supervisor',
      route: '/supervisor/dashboard',
      selector: '[data-tour="sup-projects-select"]',
      title: 'Proyectos activos',
      body: 'Selecciona un proyecto para comenzar a reportar andamios.',
      placement: 'bottom',
    },
    {
      id: 'sup-scaffold-create',
      role: 'supervisor',
      route: '/supervisor/project/:projectId',
      selector: '[data-tour="sup-scaffold-create"]',
      title: 'Crear andamio',
      body: 'Desde aquí inicias un nuevo reporte de andamio.',
      placement: 'bottom',
    },
    {
      id: 'sup-scaffold-form',
      role: 'supervisor',
      route: '/supervisor/project/:projectId/create-scaffold',
      selector: '[data-tour="sup-scaffold-form"]',
      title: 'Formulario del andamio',
      body: 'Completa dimensiones, área, TAG y ubicación. El sistema calcula m³ automáticamente.',
      placement: 'bottom',
    },
    {
      id: 'sup-scaffold-photos',
      role: 'supervisor',
      route: '/supervisor/project/:projectId/create-scaffold',
      selector: '[data-tour="sup-scaffold-photos"]',
      title: 'Evidencia fotográfica',
      body: 'Adjunta la foto del andamio; es obligatoria para reportar.',
      placement: 'bottom',
    },
    {
      id: 'sup-scaffold-actions',
      role: 'supervisor',
      route: '/supervisor/project/:projectId',
      selector: '[data-tour="sup-scaffold-actions"]',
      title: 'Acciones del andamio',
      body: 'Cuando el andamio esté 100% armado podrás cambiar la tarjeta y registrar el desarmado con foto.',
      placement: 'top',
    },
    {
      id: 'sup-tour-launcher',
      role: 'supervisor',
      route: '*',
      selector: '[data-tour="tour-launcher"]',
      title: '¿Necesitas ayuda?',
      body: 'Este botón siempre te permite reabrir la guía cuando la necesites.',
      placement: 'top',
      mobilePlacement: 'top',
    },
  ],
  client: [
    {
      id: 'client-projects',
      role: 'client',
      route: '/client/dashboard',
      selector: '[data-tour="client-projects"]',
      title: 'Tus proyectos',
      body: 'Aquí ves los proyectos asignados a tu empresa. Entra para revisar métricas y andamios.',
      placement: 'bottom',
    },
    {
      id: 'client-metrics',
      role: 'client',
      route: '/client/project/:projectId',
      selector: '[data-tour="client-metrics"]',
      title: 'Dashboard del proyecto',
      body: 'Revisa métricas clave como avances, metros cúbicos y estados de andamios.',
      placement: 'bottom',
    },
    {
      id: 'client-scaffolds',
      role: 'client',
      route: '/client/project/:projectId',
      selector: '[data-tour="client-scaffolds"]',
      title: 'Andamios y detalles',
      body: 'Aquí puedes ver los andamios del proyecto. Al abrir uno podrás revisar fotos y dejar notas.',
      placement: 'bottom',
    },
    {
      id: 'client-gallery',
      role: 'client',
      route: '/client/project/:projectId',
      selector: '[data-tour="client-gallery"]',
      title: 'Galería de fotos',
      body: 'Accede a la galería con evidencia fotográfica del proyecto.',
      placement: 'bottom',
    },
    {
      id: 'client-pdf',
      role: 'client',
      route: '/client/project/:projectId',
      selector: '[data-tour="client-pdf"]',
      title: 'Reporte en PDF',
      body: 'Descarga el reporte del proyecto cuando necesites compartirlo.',
      placement: 'bottom',
    },
    {
      id: 'client-tour-launcher',
      role: 'client',
      route: '*',
      selector: '[data-tour="tour-launcher"]',
      title: '¿Necesitas ayuda?',
      body: 'Este botón siempre te permite reabrir la guía cuando la necesites.',
      placement: 'top',
      mobilePlacement: 'top',
    },
  ],
};

export const contextualStepsByRole: Record<TourRole, TourStep[]> = {
  admin: [
    {
      id: 'admin-clients-create',
      role: 'admin',
      route: '/admin/clients',
      selector: '[data-tour="admin-clients-create"]',
      title: 'Crear empresa cliente',
      body: 'Primero registra la empresa cliente. Luego podrás crear proyectos y usuarios asociados.',
      placement: 'bottom',
    },
    {
      id: 'admin-clients-list',
      role: 'admin',
      route: '/admin/clients',
      selector: '[data-tour="admin-clients-list"]',
      title: 'Listado de clientes',
      body: 'Aquí ves todas las empresas. Revisa su estado antes de crear nuevos proyectos.',
      placement: 'top',
    },
    {
      id: 'admin-users-create',
      role: 'admin',
      route: '/admin/users',
      selector: '[data-tour="admin-users-create"]',
      title: 'Crear usuarios',
      body: 'Crea usuarios cliente y supervisor para operar los proyectos. Luego asigna sus accesos.',
      placement: 'bottom',
    },
    {
      id: 'admin-users-filter',
      role: 'admin',
      route: '/admin/users',
      selector: '[data-tour="admin-users-filter"]',
      title: 'Filtrar por rol',
      body: 'Filtra por rol para encontrar usuarios rápido antes de editar o eliminar.',
      placement: 'bottom',
    },
    {
      id: 'admin-users-list',
      role: 'admin',
      route: '/admin/users',
      selector: '[data-tour="admin-users-list"]',
      title: 'Gestión de usuarios',
      body: 'Desde aquí puedes editar o eliminar usuarios según permisos y estado.',
      placement: 'top',
    },
    {
      id: 'admin-projects-create',
      role: 'admin',
      route: '/admin/projects',
      selector: '[data-tour="admin-projects-create"]',
      title: 'Crear proyecto',
      body: 'Define el proyecto y el cliente asociado. Sin cliente no se puede reportar.',
      placement: 'bottom',
    },
    {
      id: 'admin-projects-filters',
      role: 'admin',
      route: '/admin/projects',
      selector: '[data-tour="admin-projects-filters"]',
      title: 'Estado del proyecto',
      body: 'Puedes mostrar proyectos desactivados para reactivarlos o revisar historial.',
      placement: 'bottom',
    },
    {
      id: 'admin-projects-assign',
      role: 'admin',
      route: '/admin/projects',
      selector: '[data-tour="admin-projects-assign"]',
      title: 'Asignar usuarios',
      body: 'Asigna supervisor y cliente antes de comenzar a reportar andamios.',
      placement: 'top',
    },
    {
      id: 'admin-userhistory-search',
      role: 'admin',
      route: '/admin/users/:userId/history',
      selector: '[data-tour="admin-userhistory-search"]',
      title: 'Buscar cambios',
      body: 'Filtra por proyecto o número de andamio para encontrar eventos específicos.',
      placement: 'bottom',
    },
    {
      id: 'admin-userhistory-list',
      role: 'admin',
      route: '/admin/users/:userId/history',
      selector: '[data-tour="admin-userhistory-list"]',
      title: 'Historial del usuario',
      body: 'Revisa acciones realizadas por el usuario para auditoría y trazabilidad.',
      placement: 'top',
    },
    {
      id: 'admin-userform-role-new',
      role: 'admin',
      route: '/admin/users/new',
      selector: '[data-tour="admin-userform-role"]',
      title: 'Definir rol',
      body: 'Selecciona el rol correcto para otorgar permisos adecuados.',
      placement: 'bottom',
    },
    {
      id: 'admin-userform-password-new',
      role: 'admin',
      route: '/admin/users/new',
      selector: '[data-tour="admin-userform-password"]',
      title: 'Contraseña inicial',
      body: 'Define una contraseña segura para el primer acceso del usuario.',
      placement: 'bottom',
    },
    {
      id: 'admin-userform-actions-new',
      role: 'admin',
      route: '/admin/users/new',
      selector: '[data-tour="admin-userform-actions"]',
      title: 'Guardar usuario',
      body: 'Confirma la creación del usuario o cancela si falta información.',
      placement: 'top',
    },
    {
      id: 'admin-userform-role-edit',
      role: 'admin',
      route: '/admin/users/edit/:id',
      selector: '[data-tour="admin-userform-role"]',
      title: 'Actualizar rol',
      body: 'Ajusta permisos cuando cambien las responsabilidades del usuario.',
      placement: 'bottom',
    },
    {
      id: 'admin-userform-password-edit',
      role: 'admin',
      route: '/admin/users/edit/:id',
      selector: '[data-tour="admin-userform-password"]',
      title: 'Cambiar contraseña',
      body: 'Deja en blanco si no deseas modificar la contraseña actual.',
      placement: 'bottom',
    },
    {
      id: 'admin-userform-actions-edit',
      role: 'admin',
      route: '/admin/users/edit/:id',
      selector: '[data-tour="admin-userform-actions"]',
      title: 'Guardar cambios',
      body: 'Guarda la actualización del usuario o cancela la edición.',
      placement: 'top',
    },
    {
      id: 'admin-scaffolds-project',
      role: 'admin',
      route: '/admin/scaffolds',
      selector: '[data-tour="admin-scaffolds-project"]',
      title: 'Seleccionar proyecto',
      body: 'Elige el proyecto para ver sus andamios y reportes.',
      placement: 'bottom',
    },
    {
      id: 'admin-scaffolds',
      role: 'admin',
      route: '/admin/scaffolds',
      selector: '[data-tour="admin-scaffolds"]',
      title: 'Accesos rápidos',
      body: 'Crear andamio, ver galería y exportar reportes desde esta barra.',
      placement: 'bottom',
    },
    {
      id: 'admin-scaffolds-grid',
      role: 'admin',
      route: '/admin/scaffolds',
      selector: '[data-tour="admin-scaffolds-grid"]',
      title: 'Listado de andamios',
      body: 'Revisa el detalle de cada andamio y su estado de tarjeta.',
      placement: 'top',
    },
    {
      id: 'admin-project-gallery-filters',
      role: 'admin',
      route: '/admin/project/:projectId/gallery',
      selector: '[data-tour="project-gallery-filters"]',
      title: 'Filtros de galería',
      body: 'Filtra por estado y tipo de foto para revisar evidencia específica.',
      placement: 'bottom',
    },
    {
      id: 'admin-project-gallery-content',
      role: 'admin',
      route: '/admin/project/:projectId/gallery',
      selector: '[data-tour="project-gallery-content"]',
      title: 'Evidencia fotográfica',
      body: 'Abre una imagen para ver detalles o descargar evidencia del proyecto.',
      placement: 'top',
    },
    {
      id: 'admin-notifications-filters',
      role: 'admin',
      route: '/admin/notifications',
      selector: '[data-tour="notifications-filters"]',
      title: 'Filtrar avisos',
      body: 'Prioriza notificaciones no leídas para actuar rápido.',
      placement: 'bottom',
    },
    {
      id: 'admin-notifications-list',
      role: 'admin',
      route: '/admin/notifications',
      selector: '[data-tour="notifications-list"]',
      title: 'Actividad reciente',
      body: 'Revisa actualizaciones de proyectos y marca como leídas o elimina.',
      placement: 'top',
    },
    {
      id: 'admin-profile-picture',
      role: 'admin',
      route: '/admin/profile',
      selector: '[data-tour="profile-picture"]',
      title: 'Foto de perfil',
      body: 'Actualiza tu foto para identificarte en la plataforma.',
      placement: 'bottom',
    },
    {
      id: 'admin-profile-account',
      role: 'admin',
      route: '/admin/profile',
      selector: '[data-tour="profile-account"]',
      title: 'Datos de cuenta',
      body: 'Edita nombre, teléfono y contraseña si corresponde.',
      placement: 'top',
    },
    {
      id: 'admin-profile-save',
      role: 'admin',
      route: '/admin/profile',
      selector: '[data-tour="profile-save"]',
      title: 'Guardar cambios',
      body: 'Confirma la actualización de tu perfil.',
      placement: 'top',
    },
  ],
  supervisor: [
    {
      id: 'sup-projects-search',
      role: 'supervisor',
      route: '/supervisor/dashboard',
      selector: '[data-tour="sup-projects-search"]',
      title: 'Buscar proyecto',
      body: 'Filtra tus proyectos para encontrar el que vas a reportar hoy.',
      placement: 'bottom',
    },
    {
      id: 'sup-projects-select',
      role: 'supervisor',
      route: '/supervisor/dashboard',
      selector: '[data-tour="sup-projects-select"]',
      title: 'Entrar al proyecto',
      body: 'Selecciona un proyecto para comenzar a reportar andamios.',
      placement: 'bottom',
    },
    {
      id: 'sup-scaffold-create',
      role: 'supervisor',
      route: '/supervisor/project/:projectId',
      selector: '[data-tour="sup-scaffold-create"]',
      title: 'Crear reporte',
      body: 'Inicia un nuevo andamio. Antes de guardar, asegúrate de tener la foto lista.',
      placement: 'bottom',
    },
    {
      id: 'sup-scaffold-actions',
      role: 'supervisor',
      route: '/supervisor/project/:projectId',
      selector: '[data-tour="sup-scaffold-actions"]',
      title: 'Gestión de andamios',
      body: 'Aquí ves los reportes. Cuando estén 100% armados puedes cambiar tarjeta o desarmar con foto.',
      placement: 'top',
    },
    {
      id: 'sup-scaffold-photos',
      role: 'supervisor',
      route: '/supervisor/project/:projectId/create-scaffold',
      selector: '[data-tour="sup-scaffold-photos"]',
      title: 'Foto obligatoria',
      body: 'Toma o selecciona la imagen del andamio. Es requisito para reportar.',
      placement: 'bottom',
    },
    {
      id: 'sup-scaffold-form',
      role: 'supervisor',
      route: '/supervisor/project/:projectId/create-scaffold',
      selector: '[data-tour="sup-scaffold-form"]',
      title: 'Datos del andamio',
      body: 'Completa dimensiones, área y ubicación. Luego revisa el progreso antes de guardar.',
      placement: 'bottom',
    },
    {
      id: 'sup-history-search',
      role: 'supervisor',
      route: '/supervisor/history',
      selector: '[data-tour="sup-history-search"]',
      title: 'Buscar en el historial',
      body: 'Encuentra cambios específicos por proyecto o número de andamio.',
      placement: 'bottom',
    },
    {
      id: 'sup-history-list',
      role: 'supervisor',
      route: '/supervisor/history',
      selector: '[data-tour="sup-history-list"]',
      title: 'Registro de cambios',
      body: 'Aquí queda trazabilidad de tus reportes y actualizaciones.',
      placement: 'top',
    },
    {
      id: 'sup-disassemble-photo',
      role: 'supervisor',
      route: '/supervisor/scaffold/:scaffoldId/disassemble',
      selector: '[data-tour="sup-disassemble-photo"]',
      title: 'Foto de desmontaje',
      body: 'Adjunta la evidencia del área despejada para validar el desmontaje.',
      placement: 'bottom',
    },
    {
      id: 'sup-disassemble-notes',
      role: 'supervisor',
      route: '/supervisor/scaffold/:scaffoldId/disassemble',
      selector: '[data-tour="sup-disassemble-notes"]',
      title: 'Notas opcionales',
      body: 'Agrega observaciones relevantes antes de finalizar.',
      placement: 'bottom',
    },
    {
      id: 'sup-disassemble-submit',
      role: 'supervisor',
      route: '/supervisor/scaffold/:scaffoldId/disassemble',
      selector: '[data-tour="sup-disassemble-submit"]',
      title: 'Confirmar desmontaje',
      body: 'Confirma el cierre del andamio con la evidencia cargada.',
      placement: 'top',
    },
    {
      id: 'sup-notifications-filters',
      role: 'supervisor',
      route: '/supervisor/notifications',
      selector: '[data-tour="notifications-filters"]',
      title: 'Filtrar avisos',
      body: 'Prioriza notificaciones no leídas para reaccionar rápido.',
      placement: 'bottom',
    },
    {
      id: 'sup-notifications-list',
      role: 'supervisor',
      route: '/supervisor/notifications',
      selector: '[data-tour="notifications-list"]',
      title: 'Actividad reciente',
      body: 'Revisa cambios en proyectos y reportes.',
      placement: 'top',
    },
    {
      id: 'sup-profile-picture',
      role: 'supervisor',
      route: '/supervisor/profile',
      selector: '[data-tour="profile-picture"]',
      title: 'Foto de perfil',
      body: 'Actualiza tu foto para que el equipo te identifique.',
      placement: 'bottom',
    },
    {
      id: 'sup-profile-account',
      role: 'supervisor',
      route: '/supervisor/profile',
      selector: '[data-tour="profile-account"]',
      title: 'Datos de cuenta',
      body: 'Actualiza tu información y contraseña si es necesario.',
      placement: 'top',
    },
    {
      id: 'sup-profile-save',
      role: 'supervisor',
      route: '/supervisor/profile',
      selector: '[data-tour="profile-save"]',
      title: 'Guardar cambios',
      body: 'Confirma la actualización de tu perfil.',
      placement: 'top',
    },
  ],
  client: [
    {
      id: 'client-projects',
      role: 'client',
      route: '/client/dashboard',
      selector: '[data-tour="client-projects"]',
      title: 'Tus proyectos',
      body: 'Entra al proyecto para ver métricas, andamios y evidencia fotográfica.',
      placement: 'bottom',
    },
    {
      id: 'client-metrics',
      role: 'client',
      route: '/client/project/:projectId',
      selector: '[data-tour="client-metrics"]',
      title: 'Dashboard del proyecto',
      body: 'Revisa el avance general antes de ir al detalle de andamios.',
      placement: 'bottom',
    },
    {
      id: 'client-scaffolds',
      role: 'client',
      route: '/client/project/:projectId',
      selector: '[data-tour="client-scaffolds"]',
      title: 'Andamios del proyecto',
      body: 'Cambia a la vista de andamios para abrir uno y ver fotos o dejar notas.',
      placement: 'bottom',
    },
    {
      id: 'client-gallery',
      role: 'client',
      route: '/client/project/:projectId',
      selector: '[data-tour="client-gallery"]',
      title: 'Galería de fotos',
      body: 'Accede a la evidencia fotográfica del proyecto en un solo lugar.',
      placement: 'bottom',
    },
    {
      id: 'client-pdf',
      role: 'client',
      route: '/client/project/:projectId',
      selector: '[data-tour="client-pdf"]',
      title: 'Reporte PDF',
      body: 'Descarga el PDF cuando necesites compartir el avance con tu equipo.',
      placement: 'bottom',
    },
    {
      id: 'client-project-gallery-filters',
      role: 'client',
      route: '/client/project/:projectId/gallery',
      selector: '[data-tour="project-gallery-filters"]',
      title: 'Filtros de galería',
      body: 'Explora fotos por estado y tipo de evidencia.',
      placement: 'bottom',
    },
    {
      id: 'client-project-gallery-content',
      role: 'client',
      route: '/client/project/:projectId/gallery',
      selector: '[data-tour="project-gallery-content"]',
      title: 'Evidencia del proyecto',
      body: 'Haz clic en una imagen para verla en detalle y descargarla.',
      placement: 'top',
    },
    {
      id: 'client-notifications-filters',
      role: 'client',
      route: '/client/notifications',
      selector: '[data-tour="notifications-filters"]',
      title: 'Filtrar avisos',
      body: 'Revisa primero las notificaciones no leídas.',
      placement: 'bottom',
    },
    {
      id: 'client-notifications-list',
      role: 'client',
      route: '/client/notifications',
      selector: '[data-tour="notifications-list"]',
      title: 'Actualizaciones',
      body: 'Mantente al día con novedades de tus proyectos.',
      placement: 'top',
    },
    {
      id: 'client-profile-picture',
      role: 'client',
      route: '/client/profile',
      selector: '[data-tour="profile-picture"]',
      title: 'Foto de perfil',
      body: 'Actualiza tu foto para una mejor identificación.',
      placement: 'bottom',
    },
    {
      id: 'client-profile-account',
      role: 'client',
      route: '/client/profile',
      selector: '[data-tour="profile-account"]',
      title: 'Datos de cuenta',
      body: 'Edita tus datos y contraseña cuando sea necesario.',
      placement: 'top',
    },
    {
      id: 'client-profile-save',
      role: 'client',
      route: '/client/profile',
      selector: '[data-tour="profile-save"]',
      title: 'Guardar cambios',
      body: 'Confirma la actualización de tu perfil.',
      placement: 'top',
    },
  ],
};

export const getContextualStepsForRoute = (role: TourRole, pathname: string) => {
  const steps = contextualStepsByRole[role] || [];
  return steps.filter((step) => matchTourRoute(pathname, step.route));
};
